### ISSUE TITLE
讨论一下重构的依赖库选择及架构设计

### ISSUE THREAD

**Issue by daogangtang** [zonyitoo/shadowsocks-rust#10]
1楼占位。

**Comment by zonyitoo** [comment]
可能的选择

1. MIO Only，这种架构可能要连socks5.rs中实现的也要重构掉，而且代码到处是回调，需要实现一个状态机，不怎么推荐

2. MIO + coroutine-rs，这种实际上就是第一点的模型，但是程序结构更加像顺序执行，不会出现回调。

3. 线程池模型，此种必然不可行，因为这是个Proxy服务，每一个代理请求都要长期占用两个线程。

需要改进的点

1. 目前对称加密和[shadowsocks](https://github.com/shadowsocks/shadowsocks)一样，使用了OpenSSL和libsodium，前者导致在Windows下编译困难。因此建议使用rust-crypto，暂时牺牲支持一部分对称加密算法。

2. 扩展配置支持多用户Server（Optional），Shadowsocks协议本身只设计为个人使用，因此它只需要一个密码而不需要用户名，提供SS公共服务的一般都会把用户信息藏在密码里，然后在服务端分辨。

**Comment by daogangtang** [comment]
按第二种方式做有风险没？基础方面的。

**Comment by zonyitoo** [comment]
MIO + coroutine-rs 的话，需要先实现一套跟coroutine-rs结合的IO库。另外，如果以coroutine-rs目前的状态的话，使用线程池，每个线程跑一个EventLoop，每个线程里面再有N个协程去处理请求这种模型会比较合适。

可以提高的点就是coroutine-rs实现Work-stealing，实现像Goroutine那样的用法。

**Comment by zonyitoo** [comment]
Implemented in v0.9.12 88bed8cff723228cff868c9683b1b9f8a9cf8ce1
