### ISSUE TITLE
rust-nightly 编译出来的无法连接

### ISSUE THREAD

**Issue by sbwtw** [zonyitoo/shadowsocks-rust#17]
[ERROR] Unexpected EOF while reading initialize vector

提示这个错误，用其它客户端正常

另外，貌似选了 -u 参数后会 core dump

再另外，貌似不支持 localhost 这样的本地地址，或者 ::1 这样的 ipv6 地址，还有服务器也不支持域名

**Comment by zonyitoo** [comment]
Unexpected EOF while reading initialize vector, 这个是服务器端断开了链接。

`-u` 参数很久没有用过了，之后我会修一下它。

服务器支持域名，我自己就在用。

支持 `localhost` 或 `::1` 是什么意思？是说 client 端 listen 的地址？

**Comment by sbwtw** [comment]
就是 -b 参数指定的地址，写 127.0.0.1 是没有问题的，而 localhost 或者 ::1 是不行的，但这两个也是合法的本地地址 :-)

**Comment by sbwtw** [comment]
我刚又重新确认了一下， libev 的服务器会有这个问题，所以暂时不知道是哪里原因，服务器域名这个确实支持

**Comment by zonyitoo** [comment]
我之前测试 `libev` 后端的时候也遇到过这个问题，主要是 `libev` 版本的服务器处理网络包的方式不对。一个简单的 fix 是修改 https://github.com/zonyitoo/shadowsocks-rust/blob/master/src/relay/tcprelay/local.rs#L177

这里面由于是先把 IV 发过去，再发接下来的第一个包，而 shadowsocks 的大多数实现，包括 Python 版本的实现，都会把 IV 与后面的第一个包连在一起同时发。Python 的 Server 端可以正确处理这种情况，而  `libev` 版本不能。

**Comment by zonyitoo** [comment]
至于说 `-b` 参数不支持 `localhost` ，这个没有考虑到。不过不支持 `::1` 确实有点奇怪，算是Bug。

Ref: https://github.com/zonyitoo/shadowsocks-rust/blob/master/src/bin/local.rs#L164

**Comment by zonyitoo** [comment]
使用 `::1` 没有任何问题，猜测是因为你的客户端没有配置为使用 `::1` 的地址。不准备支持 `localhost`，感觉没什么必要。若想要同时支持 `127.0.0.1` 和 `::1`，建议使用 `0.0.0.0` 或 `::`。

**Comment by zonyitoo** [comment]
@sbwtw Ping. Are there any specific problem that haven't been solved yet? If it is not, I will close this issue.
