### ISSUE TITLE
请求提供一些二进制程序用作测试

### ISSUE THREAD

**Issue by bigtan** [zonyitoo/shadowsocks-rust#2]
作者可以在完成一些功能后提供二进制文件测试。

我在v2ex说过要给你测试的，目前有do的kvm服务器，搬瓦工的openvz，本地是win，没有Linux。

如果需要测试请联系我：bigtan@mathecoer.com，我可以协助进行测试

**Comment by clowwindy** [comment]
加密库只要提供 ECB 模式就可以自己写 CFB。

**Comment by zonyitoo** [comment]
@clowwindy 的确是的

**Comment by cxjava** [comment]
希望能提供windows上的客户端，现在rust编译老是出错：
error: linking with `gcc` failed: exit code: 1linking with `gcc` failed: exit code: 1

不知道怎么配置这个gcc。希望指点下。

**Comment by zonyitoo** [comment]
Closed because it does not support Windows currently.
