### ISSUE TITLE
KCPTUN支持

### ISSUE THREAD

**Issue by ghost** [zonyitoo/shadowsocks-rust#27]
https://github.com/xtaci/kcptun
喵喵喵喵

**Comment by paomian** [comment]
我认为没有必要支持这个特性。不仅会流量放大，而且以目前 shadowsocks 防御 gfw 的效果看，没有必要支持这个特性。

**Comment by zonyitoo** [comment]
目前GFW并没有针对shadowsocks流量作识别攻击，没有必要搞太复杂

**Comment by zonyitoo** [comment]
Close for inactivity

**Comment by axlrose** [comment]
kcptun是为了打鸡血用的，之前用搬瓦工下载几十KB/s,加了kcptun以后速 度打了鸡血上到MB/s
