### ISSUE TITLE
config 实例改为全局 static 变量。

### ISSUE THREAD

**Issue by paomian** [zonyitoo/shadowsocks-rust#30]
现在 TcpRelayServer 中的 run 函数里很多 clone，config 对于一个 shadowsocks 实例应该只会有一个，从性能和逻辑上都符合作为一个全局 static 变量实现。
@zonyitoo 如何？

**Comment by zonyitoo** [comment]
`shadowsocks`是作为一个lib存在，不应该对client的使用环境作假设。
比如，我可不可以写一个Client，读一大堆的配置文件，来分别提供服务？

**Comment by paomian** [comment]
如果是这样的话，可以用 arc 来包装一下，减少很多 clone，现在看着是在 run 方法里用 arc 包装，直接在 config struct 里面把变量声明为 arc 类型如何？

**Comment by zonyitoo** [comment]
仅在服务器启动时才会去clone来组装Arc，之后都是在Clone Arc。
在Config中声明为Arc，那么Config就不能动态修改了（Arc是Read Only的）

**Comment by zonyitoo** [comment]
2b73b7d1c7d59be1b4c7947575f1ce2ee4102b27
这个Commit把所有的Arc都改成了Rc，开销应该已经很少了
