### ISSUE TITLE
addr 变量命名的问题

### ISSUE THREAD

**Issue by paomian** [zonyitoo/shadowsocks-rust#31]
目前，别的没有发现，对于 addr 这个变量充斥了整个项目
目前应该有这么几个地址，需要明确
![image](https://cloud.githubusercontent.com/assets/2999156/19922057/df1d0ff4-a11b-11e6-856a-125782006861.png)
现在 addr 看的眼疼，可以在 addr 加上一些前缀，来减少这种混淆

**Comment by zonyitoo** [comment]
Agree

**Comment by paomian** [comment]
我想了一下可以这样命名

|单元|命名|
|----|-----|
|Agent|agent_addr|
|SSLocal|relay_addr|
|SSServer|server_addr|
|Real resoucre| real_addr|

**Comment by zonyitoo** [comment]
但远端服务器真的叫 Real Resource 么

**Comment by paomian** [comment]
真实需要访问的资源应该叫什么？

**Comment by zonyitoo** [comment]
Remote server? 我是这么叫的

**Comment by paomian** [comment]
那就叫 `remote_addr` 总感觉不是很明确。那就叫 `remote_server_addr` 吧

**Comment by paomian** [comment]
看了一下代码，这样

|单元|命名|
|----|-----|
|Agent|client_addr|
|SSLocal|relay_local_addr|
|SSServer|relay_server_addr|
|Remote server| Remote_server_addr|

**Comment by zonyitoo** [comment]
Ok

**Comment by paomian** [comment]
有几个地方有些问题，在 proxy_handshake 的时候， relay_server 和 relay_local 都使用了，不是很好命名，这里先忽略了。

**Comment by zonyitoo** [comment]
Close for inactivity.
