### ISSUE TITLE
Cargo.lock may better add to .gitignore?

### ISSUE THREAD

**Issue by TheWaWaR** [zonyitoo/shadowsocks-rust#37]
Because of this is mainly a binary project.

As an example, this seems not graceful:
> https://github.com/TheWaWaR/shadowsocks-rust/commit/9545746b05ac8090b605ab326fedb50499c289b2

**Comment by zonyitoo** [comment]
Cargo recommends binary projects to put `Cargo.lock` into version control.

**Comment by zonyitoo** [comment]
So this issue should be closed.

**Comment by TheWaWaR** [comment]
Well, my mistake.
