### ISSUE TITLE
Consider updating the dependency to domain 0.2

### ISSUE THREAD

**Issue by RunningCool** [zonyitoo/shadowsocks-rust#39]
It seems that domain 0.1 can't be built automatically by Cargo. See [Could not compile domain #11](https://github.com/partim/domain/issues/11). Is it possible to update the dependency so that it's possible to build the package w/o manually fixing the dependency issue?

**Comment by zonyitoo** [comment]
I have already upgraded it to 0.2 long time ago. https://github.com/zonyitoo/shadowsocks-rust/blob/master/Cargo.toml#L50

**Comment by RunningCool** [comment]
Ouch. It seems that the one (v1.2.1) on crates.io is not synchronized with the master branch of repo.

**Comment by zonyitoo** [comment]
Ah, I see. Just published `v1.3.0`. Please try it out.
