### ISSUE TITLE
TcpRelay does not relay IpAddresses in some cases

### ISSUE THREAD

**Issue by HAMIDx9** [zonyitoo/shadowsocks-rust#49]
Hi, 

After some debugging i noticed TcpRelaying does not relay `pure` ip addresses. Precisely tcprelay server always takes Line 73 (https://github.com/zonyitoo/shadowsocks-rust/blob/master/src/relay/tcprelay/server.rs#L73)  as the path and failed to resolve ip addresess like `1.1.1.1`. 

I faced this issue when using telegram above ss so that it was unable to connect to its servers.
I think it should be correct for UdpRelay too.

I should declare it only happens for iOS + WaterDrop (shadowsocks client) ( anyway it works for other tcprelayed domain for e.g apple push notification service) whereas it works correctly with Android Version. 

Thank you

**Comment by HAMIDx9** [comment]
A nasty fix can be matching addr in dns_resolver::resolve against parsing to IpAddr and regular functioning otherwise. 
I tested it and it worked but seems not so well to send a pr.

**Comment by zonyitoo** [comment]
Your client sends ip addresses as `DomainName` (a `String`) in socks5 request packet???

**Comment by zonyitoo** [comment]
@HAMIDx9 Does this solution work for you?

**Comment by HAMIDx9** [comment]
Sorry for being so late, yes works perfectly. 
I will test more in next few days and let you know about its result.
Thank you

**Comment by zonyitoo** [comment]
It should be Ok right? @HAMIDx9 . Closing this issue for lacking activities.

**Comment by HAMIDx9** [comment]
I'm using b1637c8 since then, thank you
