### ISSUE TITLE
failed to compile `shadowsocks-rust v1.5.0`

### ISSUE THREAD

**Issue by uncode** [zonyitoo/shadowsocks-rust#50]
Linux 4.9.4-1.el7.elrepo.x86_64 #1 SMP Mon Jan 16 14:34:22 EST 2017 x86_64 x86_64 x86_64 GNU/Linux

rustc --version
rustc 1.18.0 (03fc9d622 2017-06-06)

`
error: failed to compile `shadowsocks-rust v1.5.0`, intermediate artifacts can be found at `/tmp/cargo-install.WWP9tq5QcWJ5`

Caused by:
  failed to run custom build command for `libsodium-sys v0.0.15`
process didn't exit successfully: `/tmp/cargo-install.WWP9tq5QcWJ5/release/build/libsodium-sys-3e515ebbad4a435c/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"libsodium\"` did not exit successfully: exit code: 1\n--- stderr\nPackage libsodium was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libsodium.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'libsodium\' found\n"', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: build_script_build::main
  11: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  12: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  13: __libc_start_main
  14: <unknown>
`

**Comment by zonyitoo** [comment]
Package libsodium was not found in the pkg-config search path.\nPerhaps you should add the directory containing libsodium.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'libsodium\' found\n"

Install libsodium please.

**Comment by uncode** [comment]
ok

**Comment by zonyitoo** [comment]
@uncode [v1.6.0 release](https://github.com/shadowsocks/shadowsocks-rust/releases/tag/v1.6.0) has a static-linked binaries.
