### ISSUE TITLE
Ubuntu下没有编译成功

### ISSUE THREAD

**Issue by testcaoy7** [zonyitoo/shadowsocks-rust#8]
已安装libsodium 1.0.2 和 libssl-dev

Cargo汇报：
error: aborting due to 6 previous errors
Could not compile `collect`.

**Comment by zonyitoo** [comment]
@testcaoy7 这样就是因为 `collect` 这个库挂了，试一下`cargo update`，如果还是不行那就等几天再update一下

**Comment by testcaoy7** [comment]
还是不行，我就等几天吧。

**Comment by zonyitoo** [comment]
@testcaoy7 你用的是最新的nightly么？crates.io上的库都是跟着nightly来更新的

**Comment by testcaoy7** [comment]
是的。我是用http://www.rust-lang.org/install.html上提供的脚本
curl -s https://static.rust-lang.org/rustup.sh | sudo sh 来安装的

**Comment by zonyitoo** [comment]
@testcaoy7 那样就是最新的了，我也更新一下看看是不是我代码的问题

**Comment by zonyitoo** [comment]
@testcaoy7 好几天了都没有更新collect，我直接用git上的版本了 808f2b60a29892ad94bf085f514df9f584857f9a

可以编译，但我发现有一个Bug，运行是可以的，但是server端长时间运行可能会挂掉而退出，正在分析

**Comment by testcaoy7** [comment]
作者辛苦。。。我也去用git版本试试看。
